import Foundation

/// Swift port of open_clip's `SimpleTokenizer` (CLIP BPE, vocab 49408).
///
/// The vocabulary is reconstructed from the merges list exactly the way the
/// reference implementation builds it: 256 byte symbols, the same 256 with a
/// `</w>` suffix, one entry per merge, then the two special tokens. Token IDs
/// therefore match the reference without shipping a separate vocab file.
/// Parity is asserted against `tokenizer-fixtures.json` (generated by
/// tools/mobileclip2/convert.py) in the diagnostics harness.
///
/// Known deviation: the reference pipes input through ftfy + HTML unescape
/// before encoding. This port only normalizes whitespace and lowercases,
/// which is identical for ordinary well-formed user text.
struct CLIPTokenizer: Sendable {
    let contextLength: Int
    let sotToken: Int32
    let eotToken: Int32

    private let encoder: [String: Int32]
    private let bpeRanks: [Pair: Int]
    private let byteEncoder: [UInt8: String]

    private struct Pair: Hashable {
        let first: String
        let second: String
    }

    private struct AssetPayload: Decodable {
        let context_length: Int
        let vocab_size: Int
        let sot_token: Int32
        let eot_token: Int32
        let merges: [String]
    }

    enum TokenizerError: Error {
        case assetMissing
    }

    init(assetURL: URL) throws {
        let payload = try JSONDecoder().decode(AssetPayload.self, from: Data(contentsOf: assetURL))
        contextLength = payload.context_length
        sotToken = payload.sot_token
        eotToken = payload.eot_token

        byteEncoder = Self.bytesToUnicode()

        // Rebuild the vocab in the reference order.
        let baseSymbols = Self.orderedByteSymbols()
        var vocab: [String] = baseSymbols
        vocab.append(contentsOf: baseSymbols.map { $0 + "</w>" })

        var ranks: [Pair: Int] = [:]
        ranks.reserveCapacity(payload.merges.count)
        for (index, merge) in payload.merges.enumerated() {
            let parts = merge.split(separator: " ", maxSplits: 1).map(String.init)
            guard parts.count == 2 else { continue }
            ranks[Pair(first: parts[0], second: parts[1])] = index
            vocab.append(parts[0] + parts[1])
        }
        bpeRanks = ranks

        vocab.append("<start_of_text>")
        vocab.append("<end_of_text>")

        var enc: [String: Int32] = [:]
        enc.reserveCapacity(vocab.count)
        for (index, token) in vocab.enumerated() {
            enc[token] = Int32(index)
        }
        encoder = enc
    }

    static func bundled() throws -> CLIPTokenizer {
        guard let url = Bundle.main.url(forResource: "clip-tokenizer", withExtension: "json") else {
            throw TokenizerError.assetMissing
        }
        return try CLIPTokenizer(assetURL: url)
    }

    /// Tokenize into a fixed `contextLength` array: [SOT, tokens…, EOT, 0-pad].
    func encodeFull(_ text: String) -> [Int32] {
        var ids: [Int32] = [sotToken]
        ids.append(contentsOf: encodeBody(text))
        ids.append(eotToken)

        if ids.count > contextLength {
            ids = Array(ids.prefix(contextLength))
            ids[contextLength - 1] = eotToken
        }
        while ids.count < contextLength {
            ids.append(0)
        }
        return ids
    }

    private func encodeBody(_ text: String) -> [Int32] {
        let cleaned = Self.whitespaceClean(text).lowercased()
        guard !cleaned.isEmpty else { return [] }

        var result: [Int32] = []
        for word in Self.splitPattern(cleaned) {
            let encoded = word.utf8.compactMap { byteEncoder[$0] }.joined()
            for piece in bpe(encoded) {
                if let id = encoder[piece] {
                    result.append(id)
                }
            }
        }
        return result
    }

    private func bpe(_ token: String) -> [String] {
        guard !token.isEmpty else { return [] }
        var word = token.map(String.init)
        word[word.count - 1] += "</w>"

        if word.count == 1 { return word }

        while word.count > 1 {
            var bestRank = Int.max
            var bestIndex = -1
            for i in 0..<(word.count - 1) {
                if let rank = bpeRanks[Pair(first: word[i], second: word[i + 1])], rank < bestRank {
                    bestRank = rank
                    bestIndex = i
                }
            }
            guard bestIndex >= 0 else { break }

            let target = Pair(first: word[bestIndex], second: word[bestIndex + 1])
            var merged: [String] = []
            var i = 0
            while i < word.count {
                if i < word.count - 1, word[i] == target.first, word[i + 1] == target.second {
                    merged.append(target.first + target.second)
                    i += 2
                } else {
                    merged.append(word[i])
                    i += 1
                }
            }
            word = merged
        }
        return word
    }

    // MARK: - Reference helpers

    /// Mirrors the reference regex:
    /// `'s|'t|'re|'ve|'m|'ll|'d|[\p{L}]+|[\p{N}]|[^\s\p{L}\p{N}]+` (case-insensitive).
    private static let pattern: NSRegularExpression = {
        let raw = "'s|'t|'re|'ve|'m|'ll|'d|[\\p{L}]+|[\\p{N}]|[^\\s\\p{L}\\p{N}]+"
        // Force-unwrapping a constant pattern; covered by the fixture parity test.
        return try! NSRegularExpression(pattern: raw, options: [.caseInsensitive])
    }()

    private static func splitPattern(_ text: String) -> [String] {
        let ns = text as NSString
        let matches = pattern.matches(in: text, range: NSRange(location: 0, length: ns.length))
        return matches.map { ns.substring(with: $0.range) }
    }

    private static func whitespaceClean(_ text: String) -> String {
        let collapsed = text.replacingOccurrences(
            of: "\\s+",
            with: " ",
            options: .regularExpression
        )
        return collapsed.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// The GPT-2/CLIP byte→printable-unicode table, in reference iteration order.
    private static func orderedByteValues() -> [(byte: UInt8, scalar: Unicode.Scalar)] {
        var bs: [Int] = []
        bs.append(contentsOf: Int(33)...Int(126))   // '!'...'~'
        bs.append(contentsOf: Int(161)...Int(172))  // '¡'...'¬'
        bs.append(contentsOf: Int(174)...Int(255))  // '®'...'ÿ'

        var cs = bs
        var n = 0
        for b in 0..<256 where !bs.contains(b) {
            bs.append(b)
            cs.append(256 + n)
            n += 1
        }
        return zip(bs, cs).map { (UInt8($0), Unicode.Scalar($1)!) }
    }

    private static func bytesToUnicode() -> [UInt8: String] {
        var mapping: [UInt8: String] = [:]
        for entry in orderedByteValues() {
            mapping[entry.byte] = String(entry.scalar)
        }
        return mapping
    }

    /// Byte symbols sorted by byte value — matches
    /// `list(bytes_to_unicode().values())` (Python dict preserves insertion
    /// order of `range(256)` keys? No — the reference builds values in `bs`
    /// order, so we preserve that same order here).
    private static func orderedByteSymbols() -> [String] {
        orderedByteValues().map { String($0.scalar) }
    }
}
